_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.21
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 73728
data:
    value: Small_HI
dropout:
    value: 0.00983468338330501
ego:
    value: false
emlps:
    value: false
epochs:
    value: 100
final_dropout:
    value: 0.10527690625126304
loss:
    value: ce
lr:
    value: 0.006213266113989207
model:
    value: rgcn
n_gnn_layers:
    value: 2
n_heads:
    value: null
n_hidden:
    value: 66.00315515631006
num_neighbors:
    value:
        - 100
        - 100
ports:
    value: false
reverse_mp:
    value: false
seed:
    value: 1
tds:
    value: false
w_ce1:
    value: 1.0000182882773443
w_ce2:
    value: 9.23
